version: '3.8'

services:
  whatsapp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8001}:8001"  # Use PORT env var from cloud provider
    environment:
      - PYTHONPATH=/app
      - WHATSAPP_TEST_MODE=${WHATSAPP_TEST_MODE:-false}
      - DEBUG=${DEBUG:-false}
      - PORT=${PORT:-8001}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    # Cloud-optimized command
    command: ["python", "start_whatsapp_backend.py", "--port", "8001", "--host", "0.0.0.0", "--mode", "production"]
    
    # Resource limits for cloud deployment
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

networks:
  default:
    name: whatsapp-backend-cloud